TPSTFP-44
phfriedrich/Audit-Test-Automation pull request #24
Opened 2023-07-04 17:22 UTC by Lea-Dunkel

2023-07-05 14:06 UTC, NickiBroichhausen requested changes
ergebnis sieht schonmal gut aus aber ein paar stellen koennen noch improved werden

2023-07-05 14:06 UTC, NickiBroichhausen commented on ATAPHtmlReport/report.css
> +table {
kann das nicht auch zu konflikten fuehren. also das gilt ja fuer alle table tags in der ganzen html. wenn fbpro jetzt iwo eine table hinzufuegt sieht die dann doch auch komisch aus oder?
besser sind hier ids oder klassen

2023-07-05 14:06 UTC, NickiBroichhausen commented on ATAPHtmlReport/report.css
> +thead {
s.o.

2023-07-05 14:06 UTC, NickiBroichhausen commented on ATAPHtmlReport/report.css
> +th, td {
s.o.

2023-07-05 14:06 UTC, NickiBroichhausen commented on ATAPHtmlReport/report.css
> +tr:nth-child(even) {
s.o.

2023-07-05 14:06 UTC, NickiBroichhausen commented on ATAPHtmlReport/report.css
> +th {
s.o.

2023-07-05 14:06 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +            $html += "<div class='cell'>$technique : $successCounter / " + $Mappings[$tactic][$technique].Count + "</div>"
hier fehlt die bereits approvde funktion fuer die links. dh du musst bei dir nochmal den aktuellen approve mergen (git merge approve) und die merge konflikte resolven (viel glueck ... ). Dann sollte am ende der teil der den link erzeugt dabei sein und es keine merge konflikte mehr geben

2023-07-08 10:35 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
>  function ConvertTo-HtmlTable {
doku fehlt hier

2023-07-10 13:55 UTC, phfriedrich approved these changes

2023-07-10 13:56 UTC, phfriedrich approved these changes

2023-07-10 13:57 UTC, merged