Added colors to the technique cells
phfriedrich/Audit-Test-Automation pull request #35
Opened 2023-07-13 11:45 UTC by Lea-Dunkel

2023-07-13 20:34 UTC, NickiBroichhausen requested changes
ergebnis sieht gut aus und funktioniert auch. allerdings wuerde ich die qualitaet des codes noch etwas verbessern

2023-07-13 20:34 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +                                #htmlElement 'div' @{class='MITRETechnique'} {
warum ist das auskommentiert? das kann geloescht werden oder?

2023-07-13 20:34 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +                    htmlElement 'td' @{id='MITREtbody'; class =$colorClass} {
wird die id MITREtbody ueberhaupt genutzt?

2023-07-13 20:34 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
>          htmlElement 'tbody' @{id='MITREtbody'} {
wird die id MITREtbody ueberhaupt genutzt?

2023-07-13 20:34 UTC, NickiBroichhausen commented on ATAPHtmlReport/report.css
> +    border: 1px solid #000000 !important;
important sollte nicht verwendet werden, geht das auch anderster?

2023-07-13 20:34 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +                    htmlElement 'td' @{id='MITREtbody'; class =$colorClass} {
die variable colorClass ist an der stelle noch gar nicht initialisiert, dementsprechend ist die am ende auch gar nicht in der html, sollte also entfernt werden

2023-07-13 20:34 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +                            htmlElement 'div' @{id='MITRETechniques'; class=Get-ColorValue $successCounter $Mappings[$tactic][$technique].Count} {
dieses div ist das gleiche wie in zeile 839, sollte also auch entfernt werden

2023-07-13 20:34 UTC, NickiBroichhausen commented on ATAPHtmlReport/report.css
> +    /*padding: 8px;*/
wenns auskommentiert ist kanns auch geloescht werden

2023-07-13 20:34 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +									htmlElement 'div' @{id='MITRETechniques'; class=$colorClass} {
die id MITRETechniques wird mehrmals verwendet und sollte daher wahrscheinlich eher eine class sein. Zudem faend ich singular auch passender vom namen her

2023-07-13 20:34 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +		and colours the cells
doku find ich super, aber kannst du noch .PARAMETER und .EXAMPLE hinzufuegen?

2023-07-13 20:34 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +									}
da die id MITREtd auch mehrmals verwendet wird wuerde ich daraus eine class machen

2023-07-13 20:34 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +									}
wird aber auch gar nicht verwendet als am besten einfach loeschen

2023-07-19 07:43 UTC, swalbart approved these changes
css-änderunen wurden umgesetzt
example-aufruf im HTML wurde hinzugefügt

2023-07-19 17:15 UTC, NickiBroichhausen requested changes

2023-07-19 20:17 UTC, NickiBroichhausen requested changes
mein vorschlag:
```
        htmlElement 'tbody' @{id='MITREtbody'} {
            htmlElement 'tr' @{} {
                foreach ($tactic in $Mappings.Keys) {
                    htmlElement 'td' @{} {
                        foreach ($technique in $Mappings[$tactic].Keys){
							$successCounter = 0
							foreach ($id in $Mappings[$tactic][$technique].Keys) {
								if($Mappings[$tactic][$technique][$id] -eq $true){
									$successCounter++
								}
							}
							$url = get-MitreLink -technique -id $technique
							$colorClass = Get-ColorValue $successCounter $Mappings[$tactic][$technique].Count
							htmlElement 'div' @{class="MITRETechnique $colorClass"} {
								htmlElement 'a' @{href = $url } { "$technique" } 
								htmlElement 'span' @{} {": $successCounter /" + $Mappings[$tactic][$technique].Count}
							}
                        }
                    }
                }
            }
        }
```
und im css:
        
```
.MITRETechnique {
	padding: 8px;
    border: 1px solid #000000;
}
```

2023-07-20 08:21 UTC, NickiBroichhausen approved these changes

2023-07-20 09:17 UTC, merged