Ticket_TPSTFP-81
phfriedrich/Audit-Test-Automation pull request #37
Opened 2023-07-17 09:57 UTC by Xarristo

2023-07-17 18:55 UTC, phfriedrich requested changes

2023-07-17 18:55 UTC, phfriedrich commented on ATAPHtmlReport/ATAPHtmlReport.psm1
>  		#start the excel com to make its API available
Der Kommentar passt nicht mehr zu dem was hier gemacht wird, bitte anpassen

2023-07-17 18:55 UTC, phfriedrich commented on ATAPHtmlReport/enterprise-attack-v13-techniques.json
Kenne mich da zwar jetzt nicht so hundert Prozent aus, aber ist das nicht doppelt gemoppelt? 
Wir haben einmal den Identifier, der ja die Technik-ID ist und dann nochmal ein Feld "ID". 
Kann man nicht den Wert aus dem Identifier benutzen?

2023-07-17 18:55 UTC, phfriedrich commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +			$tactics = Get-MitreTactics -TechniqueID $techniques.$technique.'ID'
Siehe Kommentar zur JSON-Datei.

2023-07-18 07:58 UTC, Xarristo commented on ATAPHtmlReport/enterprise-attack-v13-techniques.json
Prinzipiell würde es schon gehen, aber die andere JSON-Datei hatte auch die Recommendation ID als Indentifier und nochmal als Feld. Außerdem war der Gedanke einen einheitlichen Zugriff für ID und Name zu haben.

2023-07-18 08:01 UTC, Xarristo commented on ATAPHtmlReport/ATAPHtmlReport.psm1
>  		#start the excel com to make its API available
angepasst

2023-07-18 08:44 UTC, merged