Ticket_TPSTFP-94
phfriedrich/Audit-Test-Automation pull request #46
Opened 2023-07-24 10:45 UTC by Xarristo

Added funciton to check if the report is compatible with the current mitre heatmap.

2023-07-24 14:17 UTC, NickiBroichhausen requested changes
Kannst du die Version unseres mappings auch noch in den Reports bei `BasedOn` ergaenzen?
also `"MITRE ATT&CK Mapping (based on CIS Microsoft Windows 10 Enterprise Release 21H1 Benchmark (Version: 1.12.0)), Version 1.0.0, Date: 2023-07-13"`

und geht das laut tobis recherche nicht auch fuer `Microsoft Windows 10 Stand-alone` und `Microsoft Windows 11 Stand-alone`?

2023-07-24 17:56 UTC, phfriedrich commented
In dem Zuge müsste wohl auch noch die Funktion Compare-EqualCISVersions angepasst werden. 
Die wird grade nur bei Windows 10 Reports ausgeführt.

2023-07-25 09:47 UTC, Xarristo commented
BasedOn wurde jetzt auch bei Windows 10 Stand-alone, Windows 11 + Stand-alone und Windows Server 2019+2022 ergänzt.
Stand-alone und nicht Stand-alone haben den gleichen Titel, also ist dort keine Anpassung notwendig.
Die Funktion Compare-EqualCISVersions wurde angepasst.

2023-07-26 12:02 UTC, NickiBroichhausen approved these changes

2023-07-26 12:05 UTC, NickiBroichhausen requested changes
win 11 in Compare-EqualCISVersions ergaenzen

2023-07-26 12:09 UTC, NickiBroichhausen approved these changes

2023-07-28 07:36 UTC, NickiBroichhausen commented
in zeile 147 steht: 						else {
							Write-Host -ForegroundColor DarkYellow "Warning: Mitre Heatmap can only be used on a Windows System together with `"Windows 10 Report`". The Mitre Heatmap will not be generated"
						}

2023-07-28 08:12 UTC, Xarristo commented
Ich habe die Fehler Meldung angepasst und die Versionen, welche jetzt Kompatibel sind ergänzt.

2023-07-28 08:45 UTC, merged