TPSTFP-95
phfriedrich/Audit-Test-Automation pull request #49
Opened 2023-07-27 15:51 UTC by Henrik1002

updated colors in caption

2023-07-28 07:23 UTC, NickiBroichhausen commented
also das wir dafuer überhaupt eigene klassen im css haben find ich ja grauenvoll, reden wir im refinemt drüber ....

2023-07-28 08:01 UTC, phfriedrich requested changes

2023-07-28 08:01 UTC, phfriedrich commented on ATAPHtmlReport/report.css
bitte noch den Farbwert für grau anpassen, der hat sich auch geändert! 
Ansonsten passt das erstmal so.

2023-07-29 08:11 UTC, phfriedrich approved these changes

2023-07-29 08:11 UTC, merged