Ticket_TPSTFP-100
phfriedrich/Audit-Test-Automation pull request #53
Opened 2023-07-31 09:02 UTC by swalbart

Visual rework of the Mitre-Report-Page

2023-08-01 19:03 UTC, NickiBroichhausen requested changes
pull request name aendern

2023-08-01 19:09 UTC, NickiBroichhausen requested changes
kannst du noch ueberschriften fuer "legende" und "Filter" einfuegen und "Current ATT&CK heatmap on tested System:" dann wieder nach ganz unten schieben.
Ansonsten sieht sehr sexy aus

2023-08-02 16:02 UTC, swalbart commented
Habe die alle Änderungen vorgenommen. Zudem habe ich die Doppelpunkte in den Überschriften entfern (wie auf anderen Tabs auch).

2023-08-02 16:06 UTC, NickiBroichhausen approved these changes
passt jetzt

2023-08-02 16:06 UTC, merged