TPSTFP-109-update-Get-ColorValue
phfriedrich/Audit-Test-Automation pull request #56
Opened 2023-08-02 16:05 UTC by Henrik1002

Updated Get-colorValue to return hex values and deleted now unused css classes

2023-08-03 08:23 UTC, NickiBroichhausen requested changes
okay hab gesehen meine filter methode ist nicht so perfekt. Der saubere Weg das zu machen ist wahrscheinlich so:

function hideMitreTechniques(checkbox){
    if (checkbox.checked) {
        for (let i = 0; i < categoryElements.length; i++) {
            categoryElements[i].style.padding = '0.1em';

            const children = categoryElements[i].querySelectorAll('*');
            for (let j = 0; j < children.length; j++) {
                children[j].style.display = 'none';
            }
        }
    } else {
        for (let i = 0; i < categoryElements.length; i++) {
            categoryElements[i].style.removeProperty('padding');

            const children = categoryElements[i].querySelectorAll('*');
            for (let j = 0; j < children.length; j++) {
                children[j].style.removeProperty('display'); 
            }
        }
    }
}




dann werden die styles nichtmehr uerberschrieben. Aktuell gehen naemlich die styles von dem div und den childs verloren

2023-08-03 13:11 UTC, Henrik1002 commented
also soll ich deine Filtermethode so anpassen und dann nochmal comitten?

2023-08-04 07:33 UTC, NickiBroichhausen commented
ja denke das ist am besten

2023-08-05 16:36 UTC, NickiBroichhausen approved these changes

2023-08-05 16:36 UTC, merged