Ticket_TPSTFP-48
phfriedrich/Audit-Test-Automation pull request #8
Opened 2023-06-22 07:39 UTC by Xarristo

Added Class MitreMap with function add to check datatypes while adding and print for printing the map.

2023-06-22 13:18 UTC, NickiBroichhausen requested changes

2023-06-22 13:18 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +		$mitreMap.Print()
dafuer haben wir jetzt die tests. Bitte eigenen test anlegen und darin den tst machen

2023-06-22 13:18 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +	[void] Print() {
ich denke das ware auch besser in den tests

2023-06-26 08:33 UTC, Xarristo commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +
Nach meinem Verständnis ist die Klasse ja nur da, um Typsicherheit erzustellen. Also macht für mich eine Add function Sinn und eine Print Methode für dem Komfort. Aber Zugegriffen würde ja eh mit einer foreach schleife oder mit "[]", wo ich keine Probleme hinsichtlich Typsicherheit sehe.

2023-06-26 11:54 UTC, NickiBroichhausen commented on ATAPHtmlReport/ATAPHtmlReport.psm1
> +
ja stimmt, waere eher komfort gewesen, kann man aber auch weglassen

2023-06-27 07:44 UTC, Xarristo commented
Habe jetzt die prints und auch Datentyp tests in eine Test Datei verschoben. Kannst du bitte nochmal prüfen, ob das so passt?

2023-06-27 08:13 UTC, NickiBroichhausen approved these changes
passt

2023-06-27 08:14 UTC, merged